### PR TITLE
Use math for overlay fill

### PR DESCRIPTION
**Pull request by docprofsky**
This gets rid of the spiral path and replaces it with maths!
Mostly tested.

### CODE REVIEW

**Comment by docprofsky** [comment]
This has been tested (by [@ajpiano](https://github.com/evil-mad/robopaint/issues/262#issuecomment-233462301) and me); it works I am ready to merge.

**Comment by techninja** [comment]
I'll review.

**Comment by techninja** [comment]
This fixes the original limitations and seems to work pretty well. Unfortunately it doesn't seem to work _any better_ than the previously somewhat UX broken one. On center weighted fills of small objects, UI locking time is wasted iterating outside of the objects bounds. Try filling a small circle and see that it takes a full 40 seconds at very fine fill precision on 10x trace speed. The UI gets no updates during this time and the progress indicator leaves because unless you give an update < 5sec, it hides itself. This is a good indicator that humans have pretty much given up unless you're telling them it's still working.

The cheat I used before was to speed through any time we weren't in the bounding box with inside iterations in a single call.. or something like that. Really there's some easy ways to speed this up that we shouldn't pass up while we're messing with it.

**Comment by techninja** [comment]
Great stuff! I guess we'll be building the beta now.

**Pull request merged**
