### PR TITLE
Add an overshoot to entire path

### PR DESCRIPTION
**Pull request by docprofsky**
This will add an overshoot to each segment of the path to account for bending in the brush. It will extend each segment of the path by the distance specified in the settings.

### CODE REVIEW

**Comment by techninja** [comment]
Have you actually _tested_ this with real hardware and a measured improvement? I want to see a before/after with a real brush painting single stroke letters from example mode, then I'll consider this.

**Comment by docprofsky** [comment]
I have tested this. Here is a photo.
img_20151004_104303

**Comment by techninja** [comment]
I'ts _amazing_ how little that sideways photo tells me.  Use an _actual_ brush with _actual letter_ paths. If this works, the letters will be readable because the brush **tip** should trace the path instead of the just the carriage (which is all a pen needs).

**Comment by oskay** [comment]
Please show a side-by-side comparison, with and without this feature.

**Comment by docprofsky** [comment]
The image above shows what this change does with pen. It is drawn using a 'z' from the text edit example mode.

In blue is the path drawn by the WCB with different overshoot settings.
Each of the short tick marks indicate the end of each segment in the path for a given offset setting, and are color coded. The green marks correspond to a 0 mm overshoot, red 8 mm, and purple 20 mm. The old overshoot code would just extend the last point out in the same direction. The new one does this for every point in the path.

**Comment by techninja** [comment]
I get that (after much looking at a sideways device), but the simple fact of the matter is that we need an actual test run of what this is meant to be fixing: brush strokes of precise lines that previously could not be accurately traced.  Again, get us a picture. I'd run it right now myself, but my bot testing space is currently taken up by a pancake extruding robot :cake:

**Comment by docprofsky** [comment]
Here is my test of the overshoot code. The bottom three rows have the same overshoot value for each row, except for the three test sets in the bottom right, which all have a 2 mm overshoot. The overshoot value is above the tests with that value.
scan0042

**Comment by techninja** [comment]
To provide closure on this: Further tests were run and it was shown that the naive implementation put forth here does "work" to improve some shapes at some sizes, but does not apply well to every issue, or to longer offsets. I'm going to go ahead and close this.

If @docprofsky is feeling ambitious he can have this reopened or just make a new one, but the work must take into account angle delta over time in regards to brush position to be viable.

**Pull request closed without merging**
